[build]
  command = "npm run build"
  publish = "Landing-page/out"

[[redirects]]
  from = "/dashboard/*"
  to = "/dist/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
